### ISSUE TITLE
Issues building utility since update

### ISSUE THREAD

**Issue by ghost** [wortiz/msh2exo#4]
I believe I followed the same process as before for building, but now I'm having problems building the utility. I guess it is possible that I did something wrong during the install but I don't think I did.

I get fatal errors after using the "cmake --build . --config Release" command for building msh2exo. Here is the error message:

[error.txt](https://github.com/wortiz/msh2exo/files/9238433/error.txt)

**Comment by wortiz** [comment]
This is from the gmsh SDK but it isn't linking correctly.

Configure with CMake option `-DENABLE_GMSH=OFF` to just use the builtin gmsh reader which you probably were doing before.

For linking with the SDK you have to follow the two `ren` rename commands from the SDK readme:

```
    C:\gmsh-git-Windows64-sdk> ren include\gmsh.h gmsh.h_original
    C:\gmsh-git-Windows64-sdk> ren include\gmsh.h_cwrap gmsh.h
    C:\gmsh-git-Windows64-sdk> cl /Iinclude share\doc\gmsh\tutorials\c++\t1.cpp lib\gmsh.lib
    C:\gmsh-git-Windows64-sdk> cd lib
    C:\gmsh-git-Windows64-sdk\lib> ..\t1.exe
```

The first two commands above.

I've added another update to find the correct Gmsh version and allow linking against the Windows SDK.

I was able to link and run with the following after those two rename commands:

```
cmake .. -DSEACASExodus_DIR=C:\src\seacas\install\lib\cmake\SEACASExodus -DCMAKE_INSTALL_PREFIX=C:\src\msh2exo\install -G "Visual Studio 16 2019" -A x64 -DGmsh_DIR=C:\gmsh-4.10.5-Windows64-sdk\ -DGmsh_LIBRARIES="C:\gmsh-4.10.5-Windows64-sdk\lib\gmsh.lib" -DENABLE_GMSH=ON -DGmsh_INCLUDE_DIRS=C:\gmsh-4.10.5-Windows64-sdk\include\
```

If you do compile with the SDK you have to pass `-b` or `--builtin` to use the builtin reader otherwise it will use the Gmsh SDK to read Gmsh files, I'm not sure which is more robust at the moment in regards to conversion.

**Comment by ghost** [comment]
Installing with -DENABLE_GMSH=OFF was successful. Also, the updates you made to grouping multiple surfaces into a physical surface worked. Thanks again!

This issue can be closed.

**Comment by wortiz** [comment]
Thanks, good to hear both things worked.
